name: todo
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dartx: ^0.2.0
  table_calendar: ^2.2.3
  path_provider: ^1.6.7
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  flutter_bloc: ^0.6.0
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.2

dev_dependencies:
  hive_generator: ^0.7.0+2
  build_runner: ^1.9.0
  flutter_test:
    sdk: flutter
dependency_overrides:
  dartx: ^0.3.0

flutter:

  uses-material-design: true
  assets:
    - images/

